# Travis CI configuration for Bites.

language: cpp
compiler:
  - g++
before_install:
# Until Travis CI upgrades g++ to 4.8 (for better C++11 support):
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get -qq install libboost1.48-all-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - alias g++ "g++-4.8"
# When Travis CI does the upgrade, replace above with below.
#  - sudo apt-get install libboost-all-dev
script:
  - scons
